  devise :invitable, 
         :database_authenticatable, 
         :registerable, 
         :confirmable,
         :recoverable,
         :rememberable, 
         :trackable,
         :validatable,
         :lockable,
         :timeoutable,
         :omniauthable
